// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0A4wAGV_eVf9tfZwRj1h3AxT7IDdgUZI',
    appId: '1:1003241522139:web:9a221f3bd512773cadddfe',
    messagingSenderId: '1003241522139',
    projectId: 'login-page-801a7',
    authDomain: 'login-page-801a7.firebaseapp.com',
    storageBucket: 'login-page-801a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKMHpkKBWXeRQiE3C5-fe27cJD-8JvXsI',
    appId: '1:1003241522139:android:03da81af65cfb163adddfe',
    messagingSenderId: '1003241522139',
    projectId: 'login-page-801a7',
    storageBucket: 'login-page-801a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQF_x1-yZGnXSLpVoZ1ypeW0qzHMdFo_c',
    appId: '1:1003241522139:ios:d7f02eb0bec8566dadddfe',
    messagingSenderId: '1003241522139',
    projectId: 'login-page-801a7',
    storageBucket: 'login-page-801a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQF_x1-yZGnXSLpVoZ1ypeW0qzHMdFo_c',
    appId: '1:1003241522139:ios:d7f02eb0bec8566dadddfe',
    messagingSenderId: '1003241522139',
    projectId: 'login-page-801a7',
    storageBucket: 'login-page-801a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0A4wAGV_eVf9tfZwRj1h3AxT7IDdgUZI',
    appId: '1:1003241522139:web:fd45cbab3266507aadddfe',
    messagingSenderId: '1003241522139',
    projectId: 'login-page-801a7',
    authDomain: 'login-page-801a7.firebaseapp.com',
    storageBucket: 'login-page-801a7.firebasestorage.app',
  );
}
